$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

binde = , xf86KbdBrightnessDown, exec, $scriptsDir/BrightnessKbd.sh --dec # decrease keyboard brightness
binde = , xf86KbdBrightnessUp, exec, $scriptsDir/BrightnessKbd.sh --inc # increase keyboard brightness

binde = , xf86MonBrightnessDown, exec, $scriptsDir/Brightness.sh --dec # decrease monitor brightness
binde = , xf86MonBrightnessUp, exec, $scriptsDir/Brightness.sh --inc # increase monitor brightness
bind = , xf86TouchpadToggle, exec, $scriptsDir/TouchPad.sh # disable touchpad

# Screenshot keybindings using F6 (no PrinSrc button)
bind = SUPER, F6, exec, $scriptsDir/ScreenShot.sh --now # screenshot
bind = SUPER SHIFT, F6, exec, $scriptsDir/ScreenShot.sh --area # screenshot (area)
bind = SUPER CTRL, F6, exec, $scriptsDir/ScreenShot.sh --in5 # # screenshot (5 secs delay)
bind = SUPER ALT, F6, exec, $scriptsDir/ScreenShot.sh --in10 # screenshot (10 secs delay)
bind = ALT, F6, exec, $scriptsDir/ScreenShot.sh --active # screenshot (active window only)

input {
	touchpad {
		tap-to-click = true
		clickfinger_behavior = true
		natural_scroll = true
		scroll_factor = 0.3
	}
}
