source = $HOME/.config/hypr/UserConfigs/UserDefaults.conf

# wallpaper stuff 
exec-once = awww-daemon --format xrgb
exec-once = awww img ~/.config/hypr/UserConfigs/Bridge.jpg

# Startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = xfsettingsd

# Polkit (Polkit Gnome / KDE)
# exec-once = /home/tcwhite/.config/hypr/scripts/Polkit.sh

# starup apps
exec-once = swaync
exec-once = waybar

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Starting hypridle to start hyprlock
exec-once = hypridle -c $HOME/.config/hypr/configs/hypridle.conf

# start gammarelay for redshift
exec-once = wl-gammarelay &
exec-once = /home/tcwhite/.config/hypr/scripts/toggle-redshift.sh reset

exec-once = hyprctl setcursor $cursor $cursorSize
env = HYPRCURSOR_THEME, $cursor
env = HYPRCURSOR_SIZE, $cursorSize
