$scriptsDir = $HOME/.config/hypr/scripts
$currentBook = $HOME/Documents/books/Rust-Book-2.pdf
$gapStep = 2

### Apps
bind = SUPER, E, exec, thunar
bind = SUPER, B, exec, firefox
bind = SUPER, O, exec, obsidian
bind = SUPER, Z, exec, zathura
bind = SUPER SHIFT, Z, exec, zathura $currentBook
bind = SUPER ALT, M, exec, prismlauncher
bind = SUPER, S, exec, pkill steam || steam

bind = SUPER, C, exec, kitty --class calcure-term -e calcure # calendar

bind = CTRL ALT SHIFT, 1, exec, $scriptsDir/toggle-kb-qwerty.py  # switch keyboard layout to qwerty
bind = CTRL ALT SHIFT, 2, exec, $scriptsDir/toggle-kb-colemak.py # switch keyboard layout to colemak-dh

bind = SUPER, Return, exec, kitty
bind = SUPER, grave, exec, kitty
bind = SUPER CTRL, Return, exec, kitty --class kitty-nvim
bind = SUPER SHIFT, N, exec, kitty --class kitty-nvim -e sh -c "nvim"

### script apps
bind = SUPER, D, exec, $scriptsDir/rofi-toggle.sh
bind = SUPER SHIFT, D, exec, $scriptsDir/rofi-toggle.sh -L

bind = SUPER ALT, E, exec, $scriptsDir/RofiEmoji.sh
bind = SUPER SHIFT, Return, exec, $scriptsDir/Dropterminal.sh kitty

# settings
bind = SUPER, G, exec, nwg-look
bind = SUPER, M, exec, kitty --class tui-term -e bluetui
bind = SUPER, N, exec, kitty --class tui-term -e wlctl
bind = SUPER SHIFT, B, exec, kitty -e btop

# Features / Extras
bind = SUPER, P,       exec, hyprpicker -a
bind = SUPER SHIFT, R, exec, $scriptsDir/Refresh.sh # Refresh waybar, swaync, rofi

# decoration scripts
bind = SUPER SHIFT, O, exec, $scriptsDir/ChangeTransparent.sh # Toggle blur settings 
bind = SUPER SHIFT, A, exec, $scriptsDir/toggleAnimations.sh  # Toggle animations on / off

bind = SUPER SHIFT, comma,  exec, $scriptsDir/ChangeGaps.sh --in  --dec $gapStep # decrease inner gaps
bind = SUPER SHIFT, period, exec, $scriptsDir/ChangeGaps.sh --in  --inc $gapStep # increase inner gaps
bind = SUPER CTRL, comma,   exec, $scriptsDir/ChangeGaps.sh --out --dec $gapStep # decrease outer gaps
bind = SUPER CTRL, period,  exec, $scriptsDir/ChangeGaps.sh --out --inc $gapStep # increase outer gaps

bind = SUPER, V, exec, $scriptsDir/ClipManager.sh # Clipboard Manager

### Window Modes
bind = SUPER, F, fullscreen
bind = SUPER, SPACE, togglefloating
# bind = SUPER ALT, SPACE, exec, hyprctl dispatch workspaceopt allfloat

### Waybar
bind = SUPER CTRL ALT, B, exec, pkill -SIGUSR1 waybar # Toggle hide/show waybar 

### User Scripts
bind = SUPER SHIFT, T, exec, $scriptsDir/toggle-redshift.sh
bind = SUPER CTRL SHIFT, K, exec, $scriptsDir/KeyBinds.sh # search keybinds via rofi

bind = SUPER ALT, L, exec, $scriptsDir/ChangeLayout.sh # Toggle Master or Dwindle Layout

