# only for Hyprland > 0.48

# browser tags
# windowrule = tag +browser, border_color rgb(2a3e70) rgb(000000), match:class ^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$

# notif tags
windowrule = tag +notif, match:class ^(swaync-control-center|swaync-notification-window|swaync-client|class)$

# terminal tags
windowrule = tag +terminal, match:class ^(Alacritty|kitty|kitty-dropterm)$

# POSITION
windowrule = center on, match:title ^(Keybindings)$
windowrule = center on, size (monitor_w*0.6) (monitor_h*0.7), match:class ^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$
windowrule = move ((monitor_w*0.72)) ((monitor_h*0.07)), float on, opacity 0.95 0.75, pin on, keep_aspect_ratio on, match:title ^(Picture-in-Picture)$

windowrule = idle_inhibit fullscreen, match:fullscreen 1

# FLOAT
windowrule = float on, opacity 0.8 0.7, size (monitor_w*0.7) (monitor_h*0.7), match:title nwg-look*

# windowrule - ######### float popups and dialogue #######
windowrule = float on, center on, match:title ^(Authentication Required)$
windowrule = float on, match:class (codium|codium-url-handler|VSCodium), match:title negative:(.*codium.*|.*VSCodium.*)
windowrule = float on, match:class ^(com.heroicgameslauncher.hgl)$, match:title negative:(Heroic Games Launcher)
windowrule = float on, match:class ^([Ss]team)$, match:title negative:^([Ss]team)$

windowrule = float on, size (monitor_w*0.7) (monitor_h*0.6), center on, match:title ^(Add Folder to Workspace)$

windowrule = float on, size (monitor_w*0.7) (monitor_h*0.6), center on, match:title ^(Save As)$

windowrule = float on, size (monitor_w*0.7) (monitor_h*0.6), match:initial_title (Open Files)

windowrule = float on, center on, size (monitor_w*0.16) (monitor_h*0.12), match:title ^(SDDM Background)$ #KooL's Dots YAD for setting SDDM background

# OPACITY
windowrule = opacity 0.97 0.95, match:tag browser*
windowrule = opacity 0.9 0.8, match:tag projects*
windowrule = opacity 0.85 0.7, match:tag file-manager*

# LAYER RULES
layerrule = blur on, ignore_alpha 0, match:namespace rofi
layerrule = blur on, ignore_alpha 0, match:namespace notifications
layerrule = blur on, ignore_alpha 0.5, match:namespace quickshell:overview

# Firefox border color 
windowrule = border_color rgb(000000) rgb(000000), match:class firefox

windowrule = float on, size (monitor_w*0.7) (monitor_h*0.7), center on, match:class tui-term

windowrule = float on, size (monitor_w*0.4) (monitor_h*0.8), move (monitor_w*0.6-50) (monitor_h*0.1), pin on, match:class calcure-term
