
$Configs = $HOME/.config/hypr/configs
$UserConfigs = $HOME/.config/hypr/UserConfigs

source = $Configs/transparent-configs/active.conf
source = $Configs/monitors.conf
source = $Configs/workspaces.conf

source = $Configs/Keybinds.conf

source = $UserConfigs/Startup_Apps.conf

source = $UserConfigs/ENVariables.conf

source = $UserConfigs/Laptops.conf

source = $UserConfigs/LaptopDisplay.conf

source = $UserConfigs/WindowRules.conf

source = $UserConfigs/UserDecorations.conf

source = $UserConfigs/UserAnimations.conf

source = $UserConfigs/UserKeybinds.conf

source = $UserConfigs/UserSettings.conf

source = $UserConfigs/UserDefaults.conf
