##### KEYBINDS #####

    # Use Ctrl-Space instead of Ctrl-b
    unbind C-b
    set -g prefix C-Space
    bind C-Space send-prefix

    ##### GENERAL #####
    set -g mouse on
    set -g history-limit 10000
    setw -g mode-keys vi

    ##### VIM-STYLE PANE NAVIGATION #####
    bind -r h select-pane -L
    bind -r j select-pane -D
    bind -r k select-pane -U
    bind -r l select-pane -R

    ##### VIM-STYLE SPLITS #####
    bind v split-window -h
    bind s split-window -v

    ##### RESIZE PANES WITH SHIFTED VIM KEYS #####
    bind -r H resize-pane -L 1
    bind -r J resize-pane -D 1
    bind -r K resize-pane -U 1
    bind -r L resize-pane -R 1

    # window navigation
    bind -r n next-window
    bind -r b previous-window

    ##### SESSION NAVIGATION #####
    # Next session (prefix + Space)
    bind Space switch-client -n
    # Previous session (prefix + Shift-Space)
    bind BSpace switch-client -p

    ##### RELOAD CONFIG #####
    bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"













##### VISUAL #####

    # Left side: [session] windows list
    set -g status-left '[#S] '
    set -g status-left-length 40

    # Show windows like: 0:window1* 1:window2-
    setw -g window-status-format '#I:#W'
    setw -g window-status-current-format '#I:#W*'

    # Right side: current pane path
    set -g status-right '#{pane_current_path} '
    set -g status-right-length 60


##### COLORS #####

    # Status bar
    set -g status-style "bg=#1e1e1e,fg=#c0c0c0"
    set -g status-left-style "fg=#5f97bb"
    set -g status-right-style "fg=#87afff"

    # Pane borders
    set -g pane-border-style "fg=#444444"
    set -g pane-active-border-style "fg=#455588"

    # Message bar
    set -g message-style "bg=#1e1e1e,fg=#ffffff"
    set -g message-command-style "bg=#1e1e1e,fg=#00afff"

    # Copy mode
    setw -g mode-style "bg=#1e1e1e,fg=#5fd7ff"

    # active / inactive window
    setw -g window-status-style 'fg=#666767'
    setw -g window-status-current-style 'fg=#dddddd,bold'













##### PLUGINS #####

    set -g @plugin 'tmux-plugins/tmux-resurrect'
    set -g @plugin 'tmux-plugins/tmux-continuum'
    set -g @continuum-restore 'on'

    # TPM plugin manager
    run '~/.tmux/plugins/tpm/tpm'
